const LOCALSTORAGE_REMOVE_GITHUB_KEY = "removeGithub";
const LOCALSTORAGE_THEME_KEY = "theme";
const LOCALSTORAGE_ID_KEY = "Id";
const LOCALSTORAGE_REFRESH_KEY = "Refresh";
const LOCALSTORAGE_ROLE_KEY = "role";

const DARK_THEME_KEY = "dark";
const LIGHT_THEME_KEY = "light";

export {
  LOCALSTORAGE_ID_KEY,
  LOCALSTORAGE_REFRESH_KEY,
  LOCALSTORAGE_REMOVE_GITHUB_KEY,
  LOCALSTORAGE_THEME_KEY,
  LOCALSTORAGE_ROLE_KEY,
  DARK_THEME_KEY,
  LIGHT_THEME_KEY,
};
