
package com.codefolio.backend.user.values;

public enum ValuesType {
    INTEGRITY,
    QUALITY,
    GROWTH,
    INNOVATION,
    HARD_WORK,
    TRANSPARENCY,
    TEAMWORK,
    RESPECT,
    TRUST,
    ACCOUNTABILITY,
    PASSION,
    FUN,
    CUSTOMER_SATISFACTION,
    SOCIAL_RESPONSIBILITY,
    DIVERSITY,
    EMPOWERMENT,
    EXCELLENCE,
    CREATIVITY,
    EFFICIENCY,
    FLEXIBILITY,
    HONESTY,
    LOYALTY,
    OPENNESS,
    RELIABILITY,
    RESPONSIVENESS,
    SUSTAINABILITY,
    TRUSTWORTHINESS
}
