package com.codefolio.backend.user.skills;

public enum SkillsType {
    // Programming Languages
    JAVA,
    JAVASCRIPT,
    TYPESCRIPT,
    PYTHON,
    RUBY,
    C,
    C_PLUS_PLUS,
    C_SHARP,
    SWIFT,
    KOTLIN,
    GO,
    RUST,
    SCALA,
    GROOVY,
    PERL,
    R,
    MATLAB,
    OBJECTIVE_C,
    ASSEMBLY,
    HASKELL,
    ERLANG,
    COBOL,
    F_SHARP,
    PHP,

    // Web & Mobile Frameworks
    SPRING_BOOT,
    DJANGO,
    FLASK,
    RUBY_ON_RAILS,
    NODEJS,
    EXPRESS_JS,
    ASP_NET,
    SPRING_MVC,
    SPRING_SECURITY,
    SPRING_CLOUD,
    STRUTS,
    JSF,
    JSP_SERVLETS,
    GRAILS,
    PLAY,
    LARAVEL,
    ZEND,
    SYMFONY,
    CAKEPHP,
    DRUPAL,
    WORDPRESS,
    JOOMLA,
    MAGENTO,
    DJANGO_REST_FRAMEWORK,
    NEXT_JS,
    GATSBY,
    BACKBONE,
    EMBER,
    METEOR,
    FLUTTER,
    REACT_NATIVE,
    IONIC,
    XAMARIN,

    // Front-end Frameworks/Libraries
    REACT,
    ANGULAR,
    VUE,
    GRAPHQL,
    APOLLO,
    PUG,
    HANDLEBARS,
    THREE_JS,
    D3_JS,
    SOCKET_IO,

    // CSS and HTML
    HTML,
    CSS,
    SASS,
    BOOTSTRAP,
    TAILWIND_CSS,

    // Database Technologies
    SQL,
    POSTGRESQL,
    MYSQL,
    MONGODB,
    SQLITE,
    ORACLE_DB,
    REDIS,
    CASSANDRA,
    COUCHDB,
    NEO4J,
    INFLUXDB,
    HBASE,

    // ORM and Database Management
    HIBERNATE,
    JPA,

    // Build & Dependency Tools
    MAVEN,
    GRADLE,
    ANT,
    WEBPACK,
    GULP,
    GRUNT,
    BABEL,
    ESLINT,
    PRETTIER,

    // Version Control Systems
    GIT,
    GITLAB,
    SVN,

    // Project Management Tools
    JIRA,

    // DevOps, Cloud, & Containers
    DOCKER,
    KUBERNETES,
    AWS,
    GCP,
    AZURE,
    OPENSTACK,
    HEROKU,
    DOCKER_SWARM,
    VAGRANT,
    PUPPET,
    CHEF,
    HELM,

    // CI/CD Tools
    JENKINS,
    TRAVIS_CI,
    CIRCLECI,
    BAMBOO,
    TEAMCITY,

    // System, Servers, & Networking
    LINUX,
    APACHE,
    NGINX,
    SHELL_SCRIPTING,
    ELASTICSEARCH,

    // Architecture & Design Patterns
    MICROSERVICES,
    EVENT_DRIVEN_ARCHITECTURE,
    CQRS,
    SERVERLESS,

    // Other Web Technologies
    WEBRTC,
    WEBASSEMBLY,
    PROGRESSIVE_WEB_APPS,
    SEARCH_ENGINE_OPTIMIZATION,
    USER_INTERFACE_DESIGN,
    USER_EXPERIENCE_DESIGN,
    ACCESSIBILITY,
    INTERNATIONALIZATION,

    // Other
    GAME_DEVELOPMENT,
    EMBEDDED_SYSTEMS,
    IOT,
    ETHEREUM,
    SOLIDITY,
    DATA_ANALYSIS,
    MACHINE_LEARNING,
    ARTIFICIAL_INTELLIGENCE,
    DEEP_LEARNING,
    BLOCKCHAIN,
    ANSIBLE,
    TERRAFORM,
    HADOOP,
    SPARK,
    FIGMA
}
