export const Services = [
  "Web Development",
  "Mobile Development",
  "Desktop Development",
  "Game Development",
  "Machine Learning",
  "Data Science",
  "Artificial Intelligence",
  "Cloud Computing",
  "Cyber Security",
  "DevOps",
  "Quality Assurance",
  "Project Management",
  "Business Analysis",
  "UI/UX Design",
  "Product Management",
  "Technical Support",
  "Technical Writing",
  "SEO Optimization",
  "E-commerce Development",
  "Content Management",
  "Database Administration",
  "Digital Marketing",
  "Graphic Design",
  "AR/VR Development",
  "Network Administration",
  "IT Consultation",
  "Systems Integration",
  "IT Strategy",
  "Hardware Development",
  "Software Training",
  "Blockchain Development",
];

export type Services = (typeof Services)[number];
